//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class enquiry
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public enquiry()
        {
            this.technicals = new HashSet<technical>();
        }
    
        public int eid { get; set; }
        public System.DateTime enquiry_date { get; set; }
        public Nullable<System.DateTime> completion_date { get; set; }
        public string enquiry_status { get; set; }
        public int uid { get; set; }
        public int pid { get; set; }
        public string description { get; set; }
    
        public virtual product product { get; set; }
        public virtual user user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<technical> technicals { get; set; }
    }
}
