//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project02.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Project_PrinterEntities : DbContext
    {
        public Project_PrinterEntities()
            : base("name=Project_PrinterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<enquiry> enquiries { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<technical> technicals { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
