//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class technical
    {
        public int tid { get; set; }
        public int eid { get; set; }
        public int uid { get; set; }
    
        public virtual enquiry enquiry { get; set; }
    }
}
